import chokidar from 'chokidar';
import { writeFileSync } from 'fs';
import path from 'path';

const inputTsPath = '../../src/shared/theme/tokens.ts';
const outputPath = '../../src/style-tokens.generated.scss';

function tokensToScss(obj: any, prefix?: string): string {
  let scss = '';

  for (const propertyName in obj) {
    const property = obj[propertyName];

    if (typeof property === 'object') {
      scss += `// ${propertyName}\n`;
      scss += tokensToScss(property, `${prefix ? prefix + '-' : ''}${propertyName}`);
      scss += '\n';
    }
    else {
      scss += `$${prefix ? prefix + '-' : ''}${propertyName}: ${property};\n`;
    }
  }

  return scss;
}

async function generateScss() {
  const { tokens } = await import(`${inputTsPath}?t=${Date.now()}`);
  console.log(tokens);
  const scssContent = `// AUTO GENERATED FROM /src/shared/theme/tokens.ts - DO NOT EDIT THIS FILE!\n${tokensToScss(tokens).trim()}`;
  writeFileSync(outputPath, scssContent);
  console.log(`[watch-style-tokens] SCSS file generated at ${outputPath}`);
}

// Initial generation.
generateScss();

// Start watching for changes.
const watcher = chokidar.watch(inputTsPath, {
  persistent: true,
});

watcher.on('change', () => {
  console.log(`[watch-style-tokens] Detected change in ${inputTsPath}, regenerating...`);
  delete require.cache[require.resolve(inputTsPath)];
  generateScss();
});